name: Jekyll site CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Um
        uses: actions/checkout@v2
      - name: Dois
        uses: helaili/jekyll-action@2.0.5
      - name: tres
        run: export JEKYLL_PAT=${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: 'gh-pages'
